---
0:               '["alpha", "0.01", "class_prior", "0.2"]'
1:               '["alpha", "0.01", "class_prior", "None"]'
10:              '["alpha", "10.0", "class_prior", "0.8", "fit_prior"]'
11:              '["alpha", "1.0", "class_prior", "0.8", "fit_prior"]'
12:              '["alpha", "1.0", "class_prior", "0.8", "fit_prior", "force_alpha"]'
13:              '["alpha", "0.1", "class_prior", "0.8", "fit_prior", "force_alpha"]'
14:              '["alpha", "0.5", "class_prior", "0.2", "fit_prior", "force_alpha"]'
15:              '["alpha", "0.1", "class_prior", "0.2", "force_alpha"]'
16:              '["alpha", "0.1", "class_prior", "0.2", "fit_prior", "force_alpha"]'
17:              '["alpha", "0.01", "class_prior", "0.2", "fit_prior"]'
18:              '["alpha", "0.01", "class_prior", "0.2", "fit_prior", "force_alpha"]'
19:              '["alpha", "0.01", "class_prior", "0.4", "fit_prior"]'
2:               '["alpha", "0.01", "class_prior", "0.4"]'
20:              '["alpha", "0.01", "class_prior", "0.4", "fit_prior", "force_alpha"]'
21:              '["alpha", "0.01", "class_prior", "0.4", "force_alpha"]'
22:              '["alpha", "0.5", "class_prior", "0.4", "force_alpha"]'
23:              '["alpha", "0.5", "class_prior", "None"]'
24:              '["alpha", "0.5", "class_prior", "None", "force_alpha"]'
25:              '["alpha", "0.5", "class_prior", "None", "fit_prior", "force_alpha"]'
26:              '["alpha", "0.01", "class_prior", "None", "fit_prior", "force_alpha"]'
27:              '["alpha", "0.01", "class_prior", "0.6", "fit_prior", "force_alpha"]'
28:              '["alpha", "0.01", "class_prior", "None", "fit_prior"]'
29:              '["alpha", "0.01", "class_prior", "0.6", "fit_prior"]'
3:               '["alpha", "0.01", "class_prior", "0.6"]'
30:              '["alpha", "0.01", "class_prior", "0.2", "force_alpha"]'
31:              '["alpha", "0.1", "class_prior", "0.2"]'
32:              '["alpha", "0.1", "class_prior", "0.2", "fit_prior"]'
33:              '["alpha", "0.1", "class_prior", "None", "fit_prior"]'
34:              '["alpha", "0.1", "class_prior", "None", "fit_prior", "force_alpha"]'
35:              '["alpha", "10.0", "class_prior", "None", "force_alpha"]'
36:              '["alpha", "10.0", "class_prior", "None", "fit_prior", "force_alpha"]'
37:              '["alpha", "10.0", "class_prior", "0.4", "fit_prior", "force_alpha"]'
38:              '["alpha", "10.0", "class_prior", "0.4", "fit_prior"]'
39:              '["alpha", "1.0", "class_prior", "0.4"]'
4:               '["alpha", "0.01", "class_prior", "0.8"]'
40:              '["alpha", "1.0", "class_prior", "0.4", "fit_prior"]'
41:              '["alpha", "1.0", "class_prior", "0.6", "fit_prior"]'
42:              '["alpha", "1.0", "class_prior", "0.6", "force_alpha"]'
43:              '["alpha", "1.0", "class_prior", "0.6", "fit_prior", "force_alpha"]'
44:              '["alpha", "0.1", "class_prior", "0.6", "fit_prior", "force_alpha"]'
45:              '["alpha", "0.1", "class_prior", "0.6", "force_alpha"]'
46:              '["alpha", "0.1", "class_prior", "None", "force_alpha"]'
47:              '["alpha", "0.1", "class_prior", "None"]'
48:              '["alpha", "1.0", "class_prior", "None"]'
49:              '["alpha", "1.0", "class_prior", "None", "fit_prior"]'
5:               '["alpha", "0.01", "class_prior", "0.8", "fit_prior"]'
50:              '["alpha", "1.0", "class_prior", "0.2", "fit_prior"]'
51:              '["alpha", "1.0", "class_prior", "0.2", "fit_prior", "force_alpha"]'
52:              '["alpha", "10.0", "class_prior", "0.2"]'
53:              '["alpha", "10.0", "class_prior", "0.2", "fit_prior"]'
54:              '["alpha", "10.0", "class_prior", "0.8"]'
55:              '["alpha", "10.0", "class_prior", "0.6"]'
56:              '["alpha", "10.0", "class_prior", "0.4"]'
57:              '["alpha", "10.0", "class_prior", "None"]'
58:              '["alpha", "10.0", "class_prior", "0.2", "force_alpha"]'
59:              '["alpha", "1.0", "class_prior", "0.2"]'
6:               '["alpha", "0.01", "class_prior", "0.8", "fit_prior", "force_alpha"]'
60:              '["alpha", "1.0", "class_prior", "0.2", "force_alpha"]'
61:              '["alpha", "0.5", "class_prior", "0.2", "force_alpha"]'
62:              '["alpha", "10.0", "class_prior", "0.2", "fit_prior", "force_alpha"]'
63:              '["alpha", "0.01", "class_prior", "None", "force_alpha"]'
64:              '["alpha", "10.0", "class_prior", "None", "fit_prior"]'
65:              '["alpha", "0.5", "class_prior", "0.2", "fit_prior"]'
66:              '["alpha", "0.5", "class_prior", "None", "fit_prior"]'
67:              '["alpha", "1.0", "class_prior", "None", "fit_prior", "force_alpha"]'
68:              '["alpha", "1.0", "class_prior", "0.4", "fit_prior", "force_alpha"]'
69:              '["alpha", "0.5", "class_prior", "0.4", "fit_prior", "force_alpha"]'
7:               '["alpha", "0.5", "class_prior", "0.8", "force_alpha"]'
70:              '["alpha", "0.5", "class_prior", "0.6", "fit_prior", "force_alpha"]'
71:              '["alpha", "10.0", "class_prior", "0.6", "fit_prior", "force_alpha"]'
72:              '["alpha", "10.0", "class_prior", "0.8", "fit_prior", "force_alpha"]'
73:              '["alpha", "0.1", "class_prior", "0.4", "fit_prior", "force_alpha"]'
74:              '["alpha", "0.1", "class_prior", "0.8", "force_alpha"]'
75:              '["alpha", "0.1", "class_prior", "0.4", "force_alpha"]'
76:              '["alpha", "0.5", "class_prior", "0.6", "force_alpha"]'
77:              '["alpha", "1.0", "class_prior", "None", "force_alpha"]'
78:              '["alpha", "1.0", "class_prior", "0.8", "force_alpha"]'
79:              '["alpha", "1.0", "class_prior", "0.4", "force_alpha"]'
8:               '["alpha", "0.5", "class_prior", "0.8", "fit_prior"]'
80:              '["alpha", "10.0", "class_prior", "0.4", "force_alpha"]'
81:              '["alpha", "10.0", "class_prior", "0.8", "force_alpha"]'
82:              '["alpha", "10.0", "class_prior", "0.6", "force_alpha"]'
83:              '["alpha", "0.5", "class_prior", "0.4"]'
84:              '["alpha", "0.1", "class_prior", "0.4"]'
85:              '["alpha", "0.5", "class_prior", "0.6"]'
86:              '["alpha", "0.1", "class_prior", "0.6"]'
87:              '["alpha", "0.5", "class_prior", "0.8"]'
88:              '["alpha", "0.1", "class_prior", "0.8"]'
89:              '["alpha", "0.5", "class_prior", "0.2"]'
9:               '["alpha", "0.5", "class_prior", "0.8", "fit_prior", "force_alpha"]'
90:              '["alpha", "1.0", "class_prior", "0.8"]'
91:              '["alpha", "1.0", "class_prior", "0.6"]'
92:              '["alpha", "0.5", "class_prior", "0.6", "fit_prior"]'
93:              '["alpha", "0.1", "class_prior", "0.6", "fit_prior"]'
94:              '["alpha", "0.1", "class_prior", "0.8", "fit_prior"]'
95:              '["alpha", "0.5", "class_prior", "0.4", "fit_prior"]'
96:              '["alpha", "0.1", "class_prior", "0.4", "fit_prior"]'
97:              '["alpha", "10.0", "class_prior", "0.6", "fit_prior"]'
98:              '["alpha", "0.01", "class_prior", "0.6", "force_alpha"]'
99:              '["alpha", "0.01", "class_prior", "0.8", "force_alpha"]'
...
