---
0:               '["alpha", "0.01"]'
1:               '["alpha", "0.01", "fit_prior"]'
10:              '["alpha", "0.1"]'
11:              '["alpha", "0.5"]'
12:              '["alpha", "10.0"]'
13:              '["alpha", "10.0", "fit_prior"]'
14:              '["alpha", "10.0", "force_alpha"]'
15:              '["alpha", "0.1", "force_alpha"]'
16:              '["alpha", "0.1", "fit_prior"]'
17:              '["alpha", "1.0", "fit_prior"]'
18:              '["alpha", "10.0", "fit_prior", "force_alpha"]'
19:              '["alpha", "0.1", "fit_prior", "force_alpha"]'
2:               '["alpha", "0.01", "fit_prior", "force_alpha"]'
3:               '["alpha", "0.5", "force_alpha"]'
4:               '["alpha", "0.5", "fit_prior"]'
5:               '["alpha", "0.5", "fit_prior", "force_alpha"]'
6:               '["alpha", "1.0", "fit_prior", "force_alpha"]'
7:               '["alpha", "1.0"]'
8:               '["alpha", "1.0", "force_alpha"]'
9:               '["alpha", "0.01", "force_alpha"]'
...
